### ISSUE TITLE
opening_hours on a fine multipolygon are not appearing

### ISSUE THREAD

**Issue by matkoniecz** [opening-hours/opening_hours_map#40]
https://www.openstreetmap.org/relation/4121283#map=16/50.0991/19.9825 is tagged but it is not appearing on http://ypid.de/~osm/?zoom=15&lat=50.09999&lon=19.98186&layers=B0T&tags=opening_hours&filter=none

**Comment by ypid** [comment]
Relations are currently not handled as you can see from the used query: https://github.com/ypid/opening_hours_map#how-does-it-work

Can you extend the query to support relations maybe?

**Comment by matkoniecz** [comment]
I think that extending it to relations would be a good idea - multipolygons are nothing atypical.

**Comment by ypid** [comment]
Right. Want to open a PR for this :wink: ?
