### ISSUE TITLE
mirror is down

### ISSUE THREAD

**Issue by matkoniecz** [opening-hours/opening_hours_map#43]
> A mirror is setup up under: http://ypid.de/~osm/

It is currently not working. Main site is working.

**Comment by ypid** [comment]
@matkoniecz Thanks for the reminder. I am aware. You should be able to use the main site for now. Sorry for the inconvenience.

**Comment by ypid** [comment]
Fixed :wink: See: https://github.com/opening-hours/opening_hours.js/issues/169
