### ISSUE TITLE
mention dependencies

### ISSUE THREAD

**Issue by matkoniecz** [opening-hours/opening_hours_map#50]
After using `make dependencies-get` `make ready-for-hosting` resulted in (among others)

`/bin/bash: jq: command not found` and `/bin/bash: bower: command not found`

**Comment by matkoniecz** [comment]
`npm install bower` is not working to get rid of the second one (Ubuntu 14.04, node v7.4.0).

**Comment by matkoniecz** [comment]
But `npm install bower -g` worked. It, in turn, caused `/bin/bash: uglifyjs: command not found` to appear.

`npm install uglify-js -g` fixed this one, and resulted in successful build.

In case that my solutions are proper ones - I can make PR to include them in the readme.

**Comment by ypid** [comment]
Sorry for the missing docs. Your instructions look good. You are welcome to include it in the readme.
