### ISSUE TITLE
Give some feedback on failure of 'git verify-commit HEAD'

### ISSUE THREAD

**Issue by matkoniecz** [opening-hours/opening_hours_map#55]
I guess that git verify-commit check in `dependencies-get` guards against potential MITM attacks that potentially would lead to execution of arbitrary code.

Butt is not at all clear what one is supposed to do in case of errors like

```
mateusz@Grisznak:~/Desktop/tmp/opening_hours_map$ make dependencies-get 
git submodule update --init
cd opening_hours.js/ && git verify-commit HEAD && git submodule update --init --recursive
gpg: Signature made nie, 19 mar 2017, 23:08:19 CET
gpg:                using RSA key 489A4D5EC353C98A
gpg: Can't check signature: public key not found
make: *** [dependencies-get] Error 1
```

(in my case I simply edited makefile to get rid of that check)

**Comment by matkoniecz** [comment]
I am guessing that one should 

- check who made the latest commit
- check what is the public key of given developer
- add public key to store of public keys used by git verify-commit

(I was worried what would happen if latest commit is made by somebody not signing commits, but as long as PRs in this repo are merged without fast forward with main author signing commits it should not happen)

**Comment by ypid** [comment]
@matkoniecz Very well summarized :+1: That is the idea. No fast forward merges or other things are done or at least I ensure that the head commit is signed and made on a (semi-)trusted machine.
