### ISSUE TITLE
Be even more newbie friendly in "helpful warning in case `git verify-commit` fails"

### ISSUE THREAD

**Issue by matkoniecz** [opening-hours/opening_hours_map#56]
I reached https://www.gnupg.org/gph/en/manual/x457.html (after some googling).

I am still not entirely sure how to find key ID (is it 489A4D5EC353C98A from `using RSA key 489A4D5EC353C98A`?')

Anyway, maybe add also explicit command necessary to obtain public key?

My attempt ended with

```
mateusz@Grisznak:~/Desktop/tmp/opening_hours_map$ gpg --keyserver certserver.pgp.com --recv-key 489A4D5EC353C98A
gpg: requesting key C353C98A from hkp server certserver.pgp.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

(is documentation that I found so old that examples mention dead servers)

next one went better

```
mateusz@Grisznak:~/Desktop/tmp/opening_hours_map$ gpg --keyserver pool.sks-keyservers.net --recv-key 489A4D5EC353C98A
gpg: requesting key C353C98A from hkp server pool.sks-keyservers.net
gpg: key C353C98A: public key "Robin Schneider (Automatic Signing Key) <ypid@riseup.net>" imported
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2017-05-26
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

but I am not entirely sure whatever I used safe keyserver and which one, if any would be better.

```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```
On `make dependencies-get` seems to indicate that I should use other keyserver.

(that is from person that I roughly aware how public key cryptography works and never interacted with gpg beyond what is exposed by add-apt-repository)

**Comment by ypid** [comment]
You can use whatever keyserver you like as long as you get the key by fingerprint. Refer to my homepage https://me.ypid.de/.

This project (same as most of my other projects) expect some level of familiarity with OpenPGP for proper authenticity checking. Ref: https://gitlab.com/ypid/fdeunlock
