### ISSUE TITLE
add option to generate list of objects on the map

### ISSUE THREAD

**Issue by matkoniecz** [opening-hours/opening_hours_map#57]
I would consider useful to have ability to expot opening hours currently visible on the map to a text-only list.

It would allow to export opening hour data to non-interactive format (main benefit is that it would be printable).

it is likely to be considered to be feature creep - in that case just close it and I will keep code in my own small fork

**Comment by ypid** [comment]
Sounds a bit like feature creep to be honest. Would an overpass API query be enough or do you mean an export of the week table e.g. calculated?

**Comment by matkoniecz** [comment]
I thought about exporting it to table, with calculated opening hours - so I can print it.

And it probably would be a feature creep.
