### ISSUE TITLE
Start map with specified coordinates

### ISSUE THREAD

**Issue by loviuz** [opening-hours/opening_hours_map#65]
Hi all,

how can I start map centered on specific coordinated? I would open the map on specific point, for example by passing coordinates in URL like openstreetmap.org. I have take a quick look at the code but it doesn't seems this feature has already been developed. Thanks in advance.

**Comment by dex2000** [comment]
In the right bottom is a link "permalink".

**Comment by ypid** [comment]
As @dex2000 said, the permalink should do what you are looking for. Example: https://openingh.openstreetmap.de/?zoom=18&lat=50.74829&lon=7.14122&layers=B0T&filter=none&tags=opening_hours
