### ISSUE TITLE
Incorrect processing of the collection_times on the map.

### ISSUE THREAD

**Issue by EinsJonas** [opening-hours/opening_hours_map#66]
Incorrect processing of the collection_times on the map.
More information in the screenshot:
<img width="581" alt="image" src="https://github.com/opening-hours/opening_hours.js/assets/52258982/d0be6109-5a87-4c71-b833-3756f9fe70a6">

**Comment by ypid** [comment]
Good catch! I did a quick fix for this. The URL parameter always worked, but when you used "configure POIs" on the page, that did not set the correct mode. This bug must have been years old.
